### ISSUE TITLE
20231205 文本更新、表格重排版

### ISSUE THREAD

**Issue by WForst-Breeze** [lingyunawa/pcl-doc#2]
文本更新主要是在难检反馈部分，其他部分的文本更新主要是将 “-” 统一替换为 “不会制作该功能。”
还有一些文本描述细节修正，详见最后一次 Edit（注释除了在 Octo 那里多加了两个 “▷”，没有更新其他内容）

拆分了表格主体，详见倒数第二次 Edit

**Comment by MoYuan-CN** [comment]
啊 这回好大..
在做了哈，可能有点慢

**Comment by WForst-Breeze** [comment]
qwq 蟹蟹……！

**Comment by MoYuan-CN** [comment]
重构！
哎 原来用了下格式化工具结果代码冗长的不得了..

**Comment by MoYuan-CN** [comment]
唔.. 在做的时候发现你的 
![image](https://github.com/lingyunawa/pcl-doc/assets/109946426/065923ba-7883-418c-a9bf-f2fa3e4aaf32)
这一条已经开始做了，或许可以移除了？

**Comment by MoYuan-CN** [comment]
![image](https://github.com/lingyunawa/pcl-doc/assets/109946426/28be1c26-b26f-4357-845c-6dc8b4f91910)
光影（396帖）部分.. 好像有点矛盾 a.a.

**Comment by WForst-Breeze** [comment]
已修改为处理中

**Comment by WForst-Breeze** [comment]
这一条是管理光影文件夹，396 的 comment 有提及

**Comment by MoYuan-CN** [comment]
那就留着吧

**Comment by MoYuan-CN** [comment]
我稍微歇会，`启动器常见问题`部分已经做好了 9ca6e1fad
预计今天中午完工

**Comment by MoYuan-CN** [comment]
啊啊啊啊啊啊啊啊啊啊啊啊啊啊终于写好了！
重构到脑子要炸了...

**Comment by MoYuan-CN** [comment]
顺便测试了下，把几个没发现的 Bug 修了
@WForst-Breeze 看看新的样式？

**Comment by WForst-Breeze** [comment]
很好看！！真的太感谢了wwwww！！
