### ISSUE TITLE
域名解析问题

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [lingyunawa/pcl-doc#21]
![image](https://github.com/PCL-Community/PCL-1930-Web/assets/160083863/6d13f19b-86f5-400f-bb9f-5e5c4928b229)
![image](https://github.com/PCL-Community/PCL-1930-Web/assets/160083863/b8964585-cd13-4f54-8323-4dc8a2f5718a)

这个解析是不是有点问题？

**Comment by MoYuan-CN** [comment]
关了（

**Comment by Deep-Dark-Forest** [comment]
其实这个链接已经失效了，凌云把网页的链接改成了https://pcl-community.github.io/PCL-1930-Web/
