### ISSUE TITLE
20231208 文本更新与建议

### ISSUE THREAD

**Issue by WForst-Breeze** [lingyunawa/pcl-doc#3]
### 建议
1. 一个小错别字
![image](https://github.com/lingyunawa/pcl-doc/assets/110760354/dfb099ff-2e5b-4241-81eb-184e79c91bf6)
2. 背景颜色使用 #15151C 等较深的颜色会不会视觉上更好一点？不过问题不大（后来试了试感觉 #22222D 也不错）

原始：
![image](https://github.com/lingyunawa/pcl-doc/assets/110760354/ef2aee56-d5a4-4045-ae2d-58ae6947c225)
#15151C：
![image](https://github.com/lingyunawa/pcl-doc/assets/110760354/cb45203d-6ba4-4835-8999-ba10dafb7943)
#22222D：
![image](https://github.com/lingyunawa/pcl-doc/assets/110760354/fd0ec5c6-769f-4b6c-9cf0-ac57d2e182ae)

### 文本更新
1. “你”->“您”
2. 添加：
![image](https://github.com/lingyunawa/pcl-doc/assets/110760354/3ef66ea6-c250-4eb8-8b9b-01d678fb5a1c)
链接：https://github.com/Hex-Dragon/PCL2/issues?q=label%3A%E7%AC%AC%E4%B8%89%E6%96%B9+is%3Aclosed
4. 补充：
![image](https://github.com/lingyunawa/pcl-doc/assets/110760354/fe266aec-a973-4c0e-a961-bc1910e8c45b)

**Comment by MoYuan-CN** [comment]
晚上要出去签个合同，一会回来整哈
背景颜色到时候我换成 Github Dark 主题一样的好了
错别字是页标题是吧

**Comment by WForst-Breeze** [comment]
是的
