### ISSUE TITLE
20240106 文本更新 + 20240107 文本更新

### ISSUE THREAD

**Issue by WForst-Breeze** [lingyunawa/pcl-doc#7]
具体信息：https://github.com/WForst-Breeze/PCL2-1930/commits/main/

#### 内容
1. 规范拼写 Optifine→OptiFine issue→Issue Curseforge→CurseForge forge→Forge
2. 删除 “迁移 Wiki 链接” 条目
3. 关键词→搜索关键词
4. PCL 消失或报毒→PCL 消失、报毒、无法更新

**Comment by MoYuan-CN** [comment]
我先投个反馈就来做
