### ISSUE TITLE
20240112 文本更新及问题

### ISSUE THREAD

**Issue by WForst-Breeze** [lingyunawa/pcl-doc#9]
![image](https://github.com/lingyunawa/pcl-doc/assets/110760354/f69edd0c-2b77-4081-b4e9-87313b8e1580)
应为 “issues” 而非 “Issues”
我估计表格正文的链接也会有类似问题，麻烦检查一下好了qwq

正文更新：
https://github.com/WForst-Breeze/PCL2-1930/commit/2b1cd6d4a9928342a41858750c96d81b753b26be

**Comment by MoYuan-CN** [comment]
issues 那个在哪里

**Comment by MoYuan-CN** [comment]
哦找到了，当时不知咋的就给那里大写了，估计是上回规范化的时候替换 issues -> Issues 时没检查出来
正文链接是 JS 生成的，没事

**Comment by MoYuan-CN** [comment]
草。居然有个 important 类型的那个特殊信息
我研究研究咋搓吧。

**Comment by JingHai-Lingyun** [comment]
草。居然有个 important 类型的那个特殊信息
我研究研究咋搓吧。

**Comment by MoYuan-CN** [comment]
做完了。剩下的两个主页加进去之后来说一声，在这里就行，不用开新的了。
~~实际是写好了的，取消注释即可~~
